# credit: https://data-dive.com/multi-os-deployment-in-cloud-using-pyinstaller-and-github-actions
name: Card Conjurer (server)
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            OUTPUT_FILE: launcher
          - os: windows-latest
            TARGET: windows
            OUTPUT_FILE: launcher.exe
          - os: ubuntu-latest
            TARGET: linux
            OUTPUT_FILE: launcher
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: |
        poetry install --no-interaction
    - name: Build with PyInstaller
      run: |
        poetry run pyinstaller launcher.spec
    - name: Upload artifact Windows
      uses: actions/upload-artifact@v3
      with:
        path: ./dist/${{ matrix.OUTPUT_FILE }}
        name: CC Server (${{ matrix.TARGET }})
